openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts app #<назва вашого додатку>
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  #<опис вашого додатку>
  description: This is a documentation of contacts app
tags: # теги, що ви будете використовувати
  - name: Contacts
    description: Operations with contacts.
  - name: Auth
    description: Auth operations.
servers:
  #- url: 'http://localhost:8080'
  - url: 'http://127.0.0.1:8080'
  - url: https://nodejs-hw-mongodb-9cc6.onrender.com #посилання на задеплоєний сайт

paths:
  # тут будуть посилання на ендпоінти
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contatcs/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml

  /auth/register:
    post:
      $ref: ../swagger/paths/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/paths/auth/login.yaml
  /auth/logout:
    post:
      $ref: ../swagger/paths/auth/logout.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/paths/auth/refresh.yaml
  /auth/sendresetemail:
    post:
      $ref: ../swagger/paths/auth/sendresetemail.yaml
  /auth/resetpassword:
    post:
      $ref: ../swagger/paths/auth/resetpassword.yaml
  /auth/getoauthurl:
    post:
      $ref: ../swagger/paths/auth/getoauthurl.yaml
  /auth/confirmoauth:
    post:
      $ref: ../swagger/paths/auth/confirmoauth.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
